name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Run workflow manually
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.paruidev.com/feeds/posts/default?alt=rss,https://dev.to/feed/pratap360,https://medium.com/feed/@Parui_Pratap"
